#!/bin/bash
python3 texlab_href.py 
sed -i 's/\[\]//g' tidied.tex
sed -i 's/\$\\,\$ *//g' tidied.tex
sed -i 's/\\[,.;:]//g' tidied.tex
sed -i '/\\begin{document}/,$!d' tidied.tex
sed -i '1s/^/\\import{preamble}\n\n' tidied.tex